# sdk @iexec/web3mail default pipeline
kind: pipeline
type: docker
name: sdk-default

trigger:
  event:
    exclude:
      - promote
steps:
  - name: install
    image: node:16
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test_node16
    image: node:16
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  - name: test_node14
    image: node:14
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  - name: npm-publish-dry-run
    image: node:16
    commands:
      - npm publish --dry-run

---
# sdk @iexec/iexec-oracle-factory-wrapper publish npm nightly pipeline
kind: pipeline
type: docker
name: sdk-publish-nightly

trigger:
  event:
    - promote
  target:
    - sdk-nightly
  branch:
    - develop

steps:
  - name: install
    image: node:16
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - test_node16:
    image: node:16
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  - test_node14:
    image: node:14
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  - name: build
    image: node:16
    commands:
      - npm run build

  - name: set-version-nightly
    image: node:16
    commands:
      - eval npm pkg set version="$(npm pkg get version)-nightly-$DRONE_COMMIT"

  - name: publish
    image: plugins/npm
    pull: always
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token
      tag: nightly
      access: public

---
# sdk @iexec/iexec-oracle-factory-wrapper publish npm latest pipeline
kind: pipeline
type: docker
name: sdk-publish-latest

trigger:
  event:
    - promote
  target:
    - sdk-latest
  branch:
    - main

steps:
  - name: install
    image: node:16
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - test_node16:
    image: node:16
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  - test_node14:
    image: node:14
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  - name: publish
    image: plugins/npm
    pull: always
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token
      tag: latest
      access: public
