pipeline:
  test_node12:
    image: node:12
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  test_node14:
    image: node:14
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  npm_publish:
    image: plugins/npm
    secrets: [npm_password]
    username: iexecteam
    email: dev@iex.ec
    tag: latest
    when:
      ref: [refs/tags/v*]
