pipeline:
  test_node16:
    image: node:16
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  test_node14:
    image: node:14
    pull: true
    commands:
      - npm ci
      - npm run build
      - npm test

  npm_publish:
    image: plugins/npm
    secrets: [npm_token]
    username: iexecteam
    email: dev@iex.ec
    tag: latest
    when:
      ref:
        include: refs/tags/v[1-9]*.*[0-9].*[0-9]
        exclude: refs/tags/v[1-9]*.*[0-9].*[0-9]-*

  npm_publish_alpha:
    image: plugins/npm
    secrets: [npm_token]
    username: iexecteam
    email: dev@iex.ec
    tag: alpha
    when:
      ref: refs/tags/v[1-9]*.*[0-9].*[0-9]-alpha.*[0-9]
